decisionchess/decisionchess/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from main.views import custom_404

urlpatterns = [
    path(settings.ADMIN_PATH, admin.site.urls),
    path('register/', include("register.urls")),
    path('', include("main.urls")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

handler404 = custom_404

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]

decisionchess/main/urls.py
# urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path("quick_pair/", views.quick_pair, name='quick_pair'),
    path("create_new_game/", views.create_new_game, name='create_new_game'),
    path("create_new_game/<uuid:optional_uuid>/", views.create_new_game, name='create_new_game_with_uuid'),
    path('check_game_availability/', views.check_game_availability, name='available'),
    path('get_private_id/', views.create_signed_key, name='private_id'),
    path('get_lobby_games/', views.get_lobby_games, name='get_lobby_games'),
    path("config/<uuid:game_uuid>/", views.get_config, name='get_game_config'),
    path('play/<uuid:game_uuid>/', views.play, name='join_new_game'),
    path('update_connected/', views.update_connected, name='update_connected'),
    path('error/<str:game_uuid>/', views.error, name='error'),
    path("game-state/<uuid:game_uuid>/", views.get_or_update_state, name='get_or_update_state'),
    path('save_game/', views.save_game, name='save_game'),
    path('report_chat/', views.report_chat, name='report_chat'),
    path("lessons/", views.lessons, name="lessons"),
    path("lessons/<str:lesson>/", views.lesson, name="lesson"),
    path("variants/", views.variants, name="variants"),
    path("news/", views.news, name="news"),
    path("live/", views.live, name='live'),
    path("board_editor/", views.board_editor, name='board_editor'),
    path("game_search/", views.game_search, name="game_search"),
    path("leaderboards/", views.leaderboards, name="leaderboards"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("inbox/", views.inbox, name="inbox"),
    path("message/<uuid:message_id>/", views.message, name="message"),
    path("usersearch/", views.user_search, name="user_search"),
    path("challenge/<uuid:challenge_id>", views.challenge, name="challenge"),
    path("save_challenge/", views.upsert_challenge, name="upsert_challenge"),
    path("block/", views.block, name="block"),
    path("existing_blocks/", views.existing_blocks, name="existing_blocks"),
    path("is_blocked/", views.is_blocked, name="is_block"),
    path("notifications/", views.notifications, name="notifications"),
    path("update_notifications/", views.update_notifications, name="update_notifications"),
    path("terms-of-service/", views.terms_of_service, name="terms"),
    path("privacy/", views.privacy_policy, name="privacy"),
    path("account/themes", views.change_themes, name="change_themes"),
    path("account/email", views.change_email, name="change_email"),
    path("account/confirm/<str:uidtoken>/<str:token>/", views.confirm_email, name='activate_account'),
    path("account/passwd", views.change_password, name="change_password"),
    path("account/profile", views.edit_profile, name="edit_profile"),
    path("account/close_account", views.close_account, name="close_account"),
]

decisionchess/register/urls.py
# urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.register, name='register'),
    path("validate/<str:uidtoken>/<str:token>/", views.activate_account, name='activate_account'),
    path("account-activation/", views.account_activated, name="account_activated"),
    path("activation-failed/", views.activation_failed, name="activation_failed"),
    path('passwd/', views.password_reset_request, name='password_reset_page'),
    path('pass_reset/<str:uidtoken>/<token>/', views.reset_pass, name='reset_request'),
    path('reset_done/', views.reset_done, name='reset_done'),
]

decisionchess/register/models.py
from django.db import models

# Create your models here.

decisionchess/register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.core.exceptions import ObjectDoesNotExist
from main.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    agree_to_terms = forms.BooleanField(
        required=True,
        initial=False,
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "agree_to_terms"]

    def clean_username(self):
        username = self.cleaned_data['username']
        if self.username.startswith("Anon") or self.username.lower() == "anonymous":
            raise forms.ValidationError("Usernames starting with 'Anon' are not allowed.")
        return username

class ResendActivationEmailForm(forms.Form):
    email = forms.EmailField(label='Email Address')

    # TODO Consider whether this init is necessary
    def __init__(self, *args, **kwargs):
        super(ResendActivationEmailForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            'email',
            Submit('submit', 'Resend Activation Email')
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            user = User.objects.get(email=email)
            if user.is_active:
                raise forms.ValidationError('This account is already active')
        except ObjectDoesNotExist:
            raise forms.ValidationError('No user with this email address found')

        return email
    
class CustomResetForm(forms.Form):
    email = forms.EmailField(label='Email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            _ = User.objects.get(email=email)
        except ObjectDoesNotExist:
            raise forms.ValidationError('No user with this email address found')

        return email
    
class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('old_password')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["new_password1"])
        if commit:
            user.save()
        return user

decisionchess/register/views.py
# views.py
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings
from django.shortcuts import render, redirect
from django.db.utils import IntegrityError
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib import messages
from django.http import HttpResponseNotFound
from main.models import UserSettings, Inbox
from base64 import binascii
from datetime import datetime, timedelta
from .forms import RegisterForm, ResendActivationEmailForm, CustomResetForm, CustomPasswordChangeForm
import jwt

User = get_user_model()

def register(request):
    if request.user and request.user.is_authenticated:
        return redirect("home")
    
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_active = False  # Mark the user as inactive until they validate their email
            user.save()

            # Generate a token for email validation
            token = default_token_generator.make_token(user)

            # Create a validation link with the user's ID and token
            payload = {
                'user_id': str(user.pk),
                'exp': datetime.utcnow() + timedelta(days=1)
            }
            uid_token = jwt.encode(payload, settings.EMAIL_KEY, algorithm='HS256')
            protocol = 'https' if request.is_secure() else 'http'
            validation_link = f"{protocol}://{get_current_site(request)}/register/validate/{uid_token}/{token}/"

            # Send an email with the validation link to the user
            subject = "Decision Chess Account Activation"
            html_message = render_to_string('registration/activation_email.html', {
                'user': user,
                'validation_link': validation_link,
            })
            from_email = 'DecisionChess <decisionchess@gmail.com>'
            to_email = form.cleaned_data.get('email')
            send_mail(subject, "", from_email, [to_email], html_message=html_message)

            return redirect("home")
    else:
        form = RegisterForm()    

    return render(request, "register/register.html", {"form": form })

def password_reset_request(request):
    if request.method == "POST":
        form = CustomResetForm(request.POST)
        if form.is_valid():
            to_email = form.cleaned_data.get('email')
            
            try:
                user = User.objects.get(email=to_email)

                if not user.is_active:
                    messages.error(request, 'User not activated')
                    form = CustomResetForm()
                    return render(request, "register/password.html", {"form": form })
                
                # Generate a token for reset link validation
                token = default_token_generator.make_token(user)

                # Create a reset link with the user's ID and token
                payload = {
                    'user_id': str(user.pk),
                    'exp': datetime.utcnow() + timedelta(days=1)
                }
                uid_token = jwt.encode(payload, settings.EMAIL_KEY, algorithm='HS256')
                protocol = 'https' if request.is_secure() else 'http'
                reset_link = f"{protocol}://{get_current_site(request)}/register/pass_reset/{uid_token}/{token}/"
                subject = "Decision Chess Password Reset"
                html_message = render_to_string('registration/passwd_reset_email.html', {
                    'user': user,
                    'reset_link': reset_link,
                })
                from_email = 'DecisionChess <decisionchess@gmail.com>'
                to_email = form.cleaned_data.get('email')
                send_mail(subject, "", from_email, [to_email], html_message=html_message)

                form = CustomResetForm()

                messages.success(request, 'Password reset email sent')
                return render(request, "register/password.html", {"form": form })
            except User.DoesNotExist:
                messages.error(request, 'No user with that email address found')
            except Exception as e:
                print(e)
                messages.error(request, f'An error occurred {e}')

    else:
        form = CustomResetForm()    

    return render(request, "register/password.html", {"form": form })
                
def reset_pass(request, uidtoken, token):
    try:
        # Decode the user ID and get the user
        decoded_payload = jwt.decode(uidtoken, settings.EMAIL_KEY, algorithms=['HS256'])
        uid = decoded_payload['user_id']
        expired = datetime.utcfromtimestamp(decoded_payload['exp'])
        if expired < datetime.utcnow():
            return HttpResponseNotFound("The resource was not found.")
        user = User.objects.get(pk=uid)

        # Check if the token is valid
        if default_token_generator.check_token(user, token):
            if request.method == "POST":
                form = CustomPasswordChangeForm(user, request.POST)
                if form.is_valid():
                    try:
                        user = form.save()

                        # Re-authenticate the user
                        update_session_auth_hash(request, user)

                        messages.success(request, 'Your password was updated')
                        return redirect("reset_done")
                    except Exception:
                        messages.error(request, 'An error occurred')
                        return HttpResponseNotFound("The resource was not found.")
            else:
                form = CustomPasswordChangeForm(user)    

            return render(request, "register/password.html", {"form": form })
    except (TypeError, ValueError, OverflowError, binascii.Error):
        # Handle exceptions, e.g., invalid user ID
        print("Error: First exception type")
        return HttpResponseNotFound("The resource was not found.")
    except IntegrityError:
        print("Error: Integrity Error")
        return HttpResponseNotFound("The resource was not found.")
    except Exception:
        return HttpResponseNotFound("The resource was not found.")

def reset_done(request):
    return render(request, "register/reset_done.html")

def activate_account(request, uidtoken, token):
    try:
        # Decode the user ID and get the user
        decoded_payload = jwt.decode(uidtoken, settings.EMAIL_KEY, algorithms=['HS256'])
        uid = decoded_payload['user_id']
        expired = datetime.utcfromtimestamp(decoded_payload['exp'])
        if expired < datetime.utcnow():
            return redirect('activation_failed')
        user = User.objects.get(pk=uid)

        # Check if the token is valid
        if default_token_generator.check_token(user, token):
            # Activate the user's account
            user.is_active = True
            user.email_reference = user.email
            user_default_settings = UserSettings()
            user.save()
            user_default_settings.user = user
            user_default_settings.save()
            new_inbox = Inbox(
                user = user,
                unread_count = 0
                )
            new_inbox.save()

            # Redirect to a success page
            return redirect('account_activated')
        else:
            # Token is invalid
            return redirect('activation_failed')
    except (TypeError, ValueError, OverflowError, binascii.Error):
        # Handle exceptions, e.g., invalid user ID
        print("Error: First exception type")
        return redirect('activation_failed')
    except IntegrityError:
        print("Error: Integrity Error")
        return redirect('activation_failed')
    except Exception:
        return redirect('activation_failed')

def account_activated(request):
    return render(request, "register/account_activated.html")

def activation_failed(request):
    if request.method == 'POST':
        form = ResendActivationEmailForm(request.POST)
        if form.is_valid():
            to_email = form.cleaned_data.get('email')
            
            try:
                user = User.objects.get(email=to_email)

                if not user.is_active:
                    # Generate a new token for email validation
                    token = default_token_generator.make_token(user)

                    # Create a new validation link with the user's ID and token
                    payload = {
                        'user_id': str(user.pk),
                        'exp': datetime.utcnow() + timedelta(days=1)  # Token expiration time
                    }
                    uid_token = jwt.encode(payload, settings.EMAIL_KEY, algorithm='HS256')
                    protocol = 'https' if request.is_secure() else 'http'
                    validation_link = f"{protocol}://{get_current_site(request)}/register/validate/{uid_token}/{token}/"

                    # Send the new activation email
                    subject = "Decision Chess Account Activation"
                    html_message = render_to_string('registration/activation_email.html', {
                        'user': user,
                        'validation_link': validation_link,
                    })
                    from_email = 'DecisionChess <decisionchess@gmail.com>'
                    send_mail(subject, "", from_email, [to_email], html_message=html_message)

                    messages.success(request, 'A new activation email has been sent to your email address')
                    
                    form = ResendActivationEmailForm()
                    return render(request, "register/activation_failed.html", {'form': form})
                else:
                    messages.error(request, 'Your account is already active')

decisionchess/register/templates/register/account_activated.html
{% extends "main/base.html" %}

{% block style %}
{% endblock %}

{% block title %}
Account Activated
{% endblock %}

{% block content %}
<div id="content", name="content", class="content">
    <div class="container-fluid" style="padding: 0;">
        <div class="row justify-content-center" style="max-width: 100%;"> <!-- max width necessary for no horizontal scrolling -->
            <div class="col-10 col-md-5">
                <h1>Your account has been activated successfully.</h1>
                <p>You can now <a href="/login">log in</a> to your account.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

decisionchess/register/templates/register/activation_failed.html
{% extends "main/base.html" %}

{% block style %}
{% endblock %}

{% block title %}
Activation Failed
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div id="content", name="content", class="content">
    <div class="container-fluid" style="padding: 0;">
        <div class="row justify-content-center" style="max-width: 100%;"> <!-- max width necessary for no horizontal scrolling -->
            <div class="col-10 col-md-5">
                <form method="post" class="from-group">
                    <h1>Activation failed.</h1>
                    <p>The activation link is invalid or has expired. Resend the email?</p>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-success">Resend</button>	
                </form>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

decisionchess/register/templates/register/password.html
{% extends "main/base.html" %}

{% block style %}
{% endblock %}

{% block title %}
Password Reset
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div id="content", name="content", class="content">
    <div class="container-fluid" style="padding: 0;">
        <div class="row justify-content-center" style="max-width: 100%;"> <!-- max width necessary for no horizontal scrolling -->
            <div class="col-10 col-md-5">
                <form method="post" class="from-group">
                    {% csrf_token %}
                    {{form|crispy}}
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <button type="submit" class="btn btn-success">Reset Password</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

decisionchess/register/templates/register/register.html
{% extends "main/base.html" %}

{% block style %}
<style>
    .nav-link {
        color: #0056b3;
    }
    .nav-link:hover {
        color: #007bff;
    }
    .nav-link.active {
        color: var(--homebutton-decision);
    }
</style>
{% endblock %}

{% block title %}
Create an Account
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div id="content", name="content", class="content">
    <div class="container-fluid" style="padding: 0;">
        <div class="row justify-content-center" style="max-width: 100%;"> <!-- max width necessary for no horizontal scrolling -->
            <div class="col-10 col-md-5">
                <form method="POST" class="form-group">
                    {% csrf_token %}
                    {{ form.username|as_crispy_field }}
                    {{ form.email|as_crispy_field }}
                    {{ form.password1|as_crispy_field }}
                    {{ form.password2|as_crispy_field }}
                    <div class="form-check" style="margin-bottom: 10px;">
                        <input class="form-check-input" type="checkbox" id="id_agree_to_terms" name="{{ form.agree_to_terms.name }}" required>
                        <label class="form-check-label" for="id_agree_to_terms">
                            I agree to the
                            <a href="#" data-toggle="modal" data-target="#termsPrivacyModal">Terms of Service and Privacy Policy</a>
                        </label>
                    </div>
                    <button type="submit" class="btn btn-success">Register</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="termsPrivacyModal" tabindex="-1" role="dialog" aria-labelledby="termsPrivacyModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <ul id="modalTabs" class="nav">
                    <li class="nav-item">
                        <a class="nav-link active" id="termsTab" data-toggle="tab" href="#termsContent">
                            <h5 class="modal-title">Terms of Service</h5>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="privacyTab" data-toggle="tab" href="#privacyContent">
                            <h5 class="modal-title" >Privacy Policy</h5>
                        </a>
                    </li>
                </ul>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="termsContent">
                        {% include "main/terms/terms_october_4.html" %}
                    </div>
                    <div class="tab-pane fade" id="privacyContent">
                        {% include "main/privacy_policy/privacy_october_4.html" %}
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#modalTabs a').on('click', function (e) {
            $('.modal-body').scrollTop(0);
        });
    });
</script>

{% endblock %}

decisionchess/register/templates/register/reset_done.html
{% extends "main/base.html" %}

{% block style %}
{% endblock %}

{% block title %}
Password Reset
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div id="content", name="content", class="content">
    <div class="container-fluid" style="padding: 0;">
        <div class="row justify-content-center" style="max-width: 100%;"> <!-- max width necessary for no horizontal scrolling -->
            <div class="col-10 col-md-5">
                <h1>Password Reset!</h1>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}